version: '2'
services:
  frpc:
    image: nykma/frp:0.23.3
    restart: always
    volumes:
      - ./config:/frp/config
      - ./log:/frp/log
    extra_hosts:
#     To visit host's port in a container,
#     you should fill in the correct IP of your docker host.
      - "dockerhost:192.168.0.64"
#   ports:
#     - "127.0.0.1:7400:7400" # admin_port

  frps:
    image: nykma/frp:0.23.3
    restart: always
    volumes:
      - ./config:/frp/config
      - ./log:/frp/log
    ports:
      - "7000:7000"     # bind_port
      - "7000:7000/udp" # kcp_bind_port
      - "7500:7500"     # dashboard_port
#     - "80:80"   # vhost_http_port
#     - "443:443" # vhost_https_port
#     # WARNING: container up/down will be VERY SLOW (even failed)
#     # if opened too much ports!
      - "20000-20020:2000-2020"
    entrypoint:
      - '/frp/frps'
      - '-c'
      - '/frp/frps.ini'
